### ISSUE TITLE
Breaks ie11/ms Edge

### ISSUE THREAD

**Issue by adietz** [cloudlace/vuetify-dialog-promise#10]
In a vue-cli created project with only vuetify added, adding this module breaks MS Edge - rendering a blank page.  The codepen sample at https://codepen.io/brikoleur/pen/MWgEbGP is also broken in MS Edge

`
import Vue from 'vue';
import App from './App.vue';
import vuetify from './plugins/vuetify';
import router from './router';

import VuetifyDialogPromise from 'vuetify-dialog-promise';

Vue.use(VuetifyDialogPromise, {
  locale: 'en',
  snackbarX: 'right',
  snackbarY: 'top',
});

new Vue({
  vuetify,
  router,
  render: h => h(App)
}).$mount('#app');
`

**Comment by brikoleur** [comment]
The error actually originates from Vuetify. This appears to be related to a problem with Babel. The optimised file served to the browser contains spread syntax for object literals, which is not supported by MSIE/Edge. Investigating...

**Comment by brikoleur** [comment]
There was a missing transpileDependencies directive in vue.config.js. You may need to add this to your project as well. Example:

```
module.exports = {
    transpileDependencies : [ "vue-i18n", "vuetify", "vuetify-dialog-promise" ]
};
```
