### ISSUE TITLE
[feature request] custom button color

### ISSUE THREAD

**Issue by mean-cj** [cloudlace/vuetify-dialog-promise#11]
Hello , thank you for your project

please options can change or custom accept, cancle button colors

thank you so much.

**Comment by brikoleur** [comment]
There is already a theme property you can set on install or when calling one of the dialogue methods. This should let you modify the button colours. See the docs on vuetify themes for details.

**Comment by mean-cj** [comment]
Hello @brikoleur 
I think if we can custom button color only in vuetify-dialog-promise is better
what do you think?

**Comment by brikoleur** [comment]
It's considered bad usability design to have different colours for the same purpose in different parts of the UI. Therefore, I feel that these dialogues should follow the general UI theme. 

I also want to keep the project as simple and minimal as possible. Basically, it's intended as a Vuetify replacement for the browser's native alert/confirm/prompt, plus simple snackbar notifications. It's not supposed to be a rich, customisable dialogue library. 

So I'm going to decline this request. However, feel free to fork the repository and make your own variant of it with the customisations you want.
