### ISSUE TITLE
Request support html on snack bar

### ISSUE THREAD

**Issue by mean-cj** [cloudlace/vuetify-dialog-promise#13]
Hello

vuetify-dialog-promise doesn't work with HTML on the message
`this.$inform( "We are the knights <br>that say Ni." );`

Cloud you please update for html support.
Thank you so much.

**Comment by brikoleur** [comment]
The difficulty with that is that the possibility to inject markup creates a potential script injection vulnerability and I really don't like those. It would make you responsible for making sure that there's nothing evil in the notifications; the way it is now with the messages escaped, this won't happen.

I'll see if I can think of a way to do it safely, like with an extra option, but no promises.

**Comment by mean-cj** [comment]
thank you. : )

**Comment by brikoleur** [comment]
I've thought about it and unfortunately there's no way I can think of to make this feature sufficiently secure against script injection, so I'm going to have to decline this request. 

If you need formatted dialogues and want to continue using this utility, you can fork it and replace the `{{ message.text }}` and `{{ text }}` in SimpleDialog.vue and SimpleSnackbar.vue with `<span v-html="message.text"></span>` and `<span v-html="text"></span>` respectively. This will inject the message as raw HTML. 

If you do this, be very very careful to only inject markup you trust (e.g. from a static localisation dictionary you've written yourself), and _never_ user inputs, either direct or indirect (e.g. from a server backend). The latter are especially dangerous as they can create persistent cross-site scripting vulnerabilities that are almost impossible to defend agains: these let the attacker do anything the user can do.

**Comment by brikoleur** [comment]
As an additional suggestion: if you're only concerned about linebreaks, you could do that through CSS `white-space: pre-break`. 

The snackbars are (by default) mounted under the Vue component that calls $inform, $warn, or $error. This means that any scoped styles you've defined for the component will apply to the snackbar as well, so you ought to be able to target the directive specifically at the snackbar.

**Comment by brikoleur** [comment]
As of version 2.2.4 newline characters will produce line breaks in dialogues and snackbars (see #14).

**Comment by mean-cj** [comment]
Hello @brikoleur 

That’s great!

Thank you so much.

**Comment by brikoleur** [comment]
Control-specific styles are supposed to be scoped, otherwise there might be collisions, especially in a general-purpose library that can be imported anywhere. If it doesn't work for you for some reason, redefine the class in your own stylesheet at the global level.
