### ISSUE TITLE
VuetifyDialogPromise.common.js big size

### ISSUE THREAD

**Issue by mean-cj** [cloudlace/vuetify-dialog-promise#16]
Hello

After analyze on nuxt build
i see VuetifyDialogPromise.common.js file big size and not minifier.

![2020-04-10_220227](https://user-images.githubusercontent.com/1191385/79000561-0eed9f80-7b77-11ea-9f0d-e62182d8f91f.jpg)

are you think?

**Comment by brikoleur** [comment]
I recommend you import the dependency and build your app using Vue CLI, that will minify and Babelize it.
