### ISSUE TITLE
Nuxt, TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by cvaize** [cloudlace/vuetify-dialog-promise#6]
I get the error "TypeError: Cannot read property 'appendChild' of null". Here is a demonstration of the error: https://codesandbox.io/embed/codesandbox-nuxt-48tq4?fontsize=14

**Comment by brikoleur** [comment]
I'm not familiar with Nuxt but it looks like you don't have a v-app node with ID "app" there. 

The inform, alert, warn, and error snackbars need to be mounted under a v-app; you can specify the ID with the snackbarParent init property if you want to use something else but "app" is the default.

So try adding a <v-app id="app"> somewhere and make sure it's mounted and try again.

**Comment by cvaize** [comment]
Indeed, you are right, it worked. There are not enough styles, but I will correct it. 
![image](https://user-images.githubusercontent.com/26907947/65254867-5e567a80-db16-11e9-9e16-db88ad8fcc39.png)

**Comment by cvaize** [comment]
Thank you! I will correct the answer, it is better to use inside the class `theme-${color}`. 
![image](https://user-images.githubusercontent.com/26907947/65255645-b0e46680-db17-11e9-9765-6fd4ba820e75.png)
