### ISSUE TITLE
Internal VueI18n overrides nuxt-i18n

### ISSUE THREAD

**Issue by goraSi** [cloudlace/vuetify-dialog-promise#9]
When using this library with Nuxt.js and nuxt-i18n module, internal VueI18n overrides prototype methods from nuxt-i18n. Is there an option to add custom i18n instance.

**Comment by brikoleur** [comment]
Currently no, but if you'll submit a pull request I'd be happy to take a look. If it doesn't break anything I'll certainly merge it.

**Comment by goraSi** [comment]
I found another library with similliar functionality. Thanks for your response.
